@startuml
scale 2
title Thanh toán tiền xăng trên PVOIL4U bằng phiếu xăng
actor "Khách hàng" as KH
participant "SSC" as SSC
KH -> SSC: Đăng nhập vào ứng dụng SSC

group KH không có key UQ
    SSC --> KH: Điều hướng KH sang luồng mở Tài khoản và ủy quyền liên kết tài khoản.
end
SSC --> KH: hiển thị màn hình nhập SSCID
KH -> SSC: KH nhập SSC IDq

@enduml